// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw7QJSTT9ZljtEiQ36zPC87hvM2UBBBbY',
    appId: '1:147016468490:web:082a24452656e8971077f3',
    messagingSenderId: '147016468490',
    projectId: 'uliral-bc390',
    authDomain: 'uliral-bc390.firebaseapp.com',
    storageBucket: 'uliral-bc390.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0o6uwH0wGJyLfrF4MStA6Hzsn8U4ApEY',
    appId: '1:147016468490:android:b2699405ba7563991077f3',
    messagingSenderId: '147016468490',
    projectId: 'uliral-bc390',
    storageBucket: 'uliral-bc390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCeIguU0qp7YdzQVvxwXf9mEoDlf2hJVg',
    appId: '1:147016468490:ios:48a44cd3f7e030bc1077f3',
    messagingSenderId: '147016468490',
    projectId: 'uliral-bc390',
    storageBucket: 'uliral-bc390.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCeIguU0qp7YdzQVvxwXf9mEoDlf2hJVg',
    appId: '1:147016468490:ios:48a44cd3f7e030bc1077f3',
    messagingSenderId: '147016468490',
    projectId: 'uliral-bc390',
    storageBucket: 'uliral-bc390.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw7QJSTT9ZljtEiQ36zPC87hvM2UBBBbY',
    appId: '1:147016468490:web:03f8756106777f7a1077f3',
    messagingSenderId: '147016468490',
    projectId: 'uliral-bc390',
    authDomain: 'uliral-bc390.firebaseapp.com',
    storageBucket: 'uliral-bc390.firebasestorage.app',
  );
}
